### ISSUE TITLE
Onboarding process

### ISSUE THREAD

**Issue by josecelano** [Nautilus-Cyberneering/.github#8]
I think it could be a good idea also to add an onboarding process section. We can start with a very simple document. This is my draft proposal @da2ce7 @cgbosse:

### First day

We will define with you your own customized onboarding plan.

### Communication

- We try to avoid private communication except for things like private data. GitHub issues, pull requests, GitHub discussions and comments are the things we mostly used.
- Email.
- We have a development Telegram chat.

### Meetings

- We only have one regular meeting a week, which we usually use to share issues about the projects, and middle-term planning.

### List of tools we use

1. Git

- [Official documentation](https://git-scm.com/doc)
- [Internal project we use to run experiments](https://github.com/Nautilus-Cyberneering/pygithub) like signing Git commits

2. PGP

We sign commits and we have started collecting good documentation for GPG on [this repo](https://github.com/Nautilus-Cyberneering/GPG-Bootcamp). GitLab and GitHub docs are also a good starting point but sometimes they do not lead you to good practices.

3. GitHub Actions

- [Official documentaion](https://github.com/features/actions).

4. DVC

- [Official documentaion](https://dvc.org/).
- [A repo to run experiments with some articles](https://github.com/josecelano/data-version-control).

5. Python

- [Good tutorials](https://realpython.com/).
- We are using [Static Typing for Python](http://mypy-lang.org/).
- WE are also using a console app framework for Python: [Typer](https://typer.tiangolo.com/).
- [Pytest](https://docs.pytest.org/en/7.1.x/)

6. TypeScript

- [TypeScript GitHub Action Template](https://github.com/actions/typescript-action).

7. Linting

- [MegaLinter](https://megalinter.github.io/latest/): 100% Open-Source tool for CI/CD workflows that analyzes consistency and quality.

**Comment by cgbosse** [comment]
Implemented the onboarding document.

**Comment by MCM-Mike** [comment]
we could also add:

- **training** , where each of us can provide some training to other people from out team in certain topics.

This is something most project lack of, sharing internal knowledge with each other and then get everyone up to the same level of knowledge in order to improve.

**Comment by cgbosse** [comment]
Adding the comments from @MCM-Mike:

- training , where each of us can provide some training to other people from out team in certain topics.
